### ISSUE TITLE
项目情况-历代记 的链接地址有误

### ISSUE THREAD

**Issue by Yinr** [LCTT/wiki#16]
[历代记](https://github.com/LCTT/wiki/blame/master/SUMMARY.md#L34) 的链接地址不对啊，`Not Found`，应该是 [README.md](https://github.com/LCTT/TranslateProject/blob/master/README.md) 么？ @wxy @bestony

**Comment by wxy** [comment]
你直接提 pr 就好~

**Comment by Yinr** [comment]
因为我有点不确定...
